language: csharp
solution: Stenography.sln
install:
  - nuget restore Stenography.sln
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Stenography.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./StenographyTests/bin/Release/StenographyTests.dll