language: csharp
solution: Stenography.sln
install:
  - nuget restore Stenography.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory packages
script:
  - xbuild /p:Configuration=Release Stenography.sln
  - ls -A
  - mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./StenographyTests/bin/Release/StenographyTests.dll