language: csharp
solution: EdSteg.sln
install:
  - nuget restore EdSteg.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory packages
script:
  - xbuild /p:Configuration=Release EdSteg.sln
  - mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./EdStegTests/bin/Release/EdStegTests.dll